[2023-11-26 15:39:33,657] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 15:39:33,693] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 15:39:33,693] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:33,693] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 15:39:33,693] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:33,728] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_province> on 2023-11-21 00:00:00+00:00
[2023-11-26 15:39:33,733] {standard_task_runner.py:52} INFO - Started process 2481 to run task
[2023-11-26 15:39:33,759] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_province', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp4j3sdup5', '--error-file', '/tmp/tmpcr5ecs5k']
[2023-11-26 15:39:33,765] {standard_task_runner.py:80} INFO - Job 36: Subtask create_dim_province
[2023-11-26 15:39:33,908] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 15:39:34,152] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_province
AIRFLOW_CTX_EXECUTION_DATE=2023-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-21T00:00:00+00:00
[2023-11-26 15:39:34,153] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 15:39:34,230] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_province, execution_date=20231121T000000, start_date=20231126T153933, end_date=20231126T153934
[2023-11-26 15:39:34,330] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 15:39:34,605] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:58:01,664] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 17:58:01,673] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 17:58:01,673] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 17:58:01,673] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 17:58:01,673] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 17:58:01,686] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_province> on 2023-11-21 00:00:00+00:00
[2023-11-26 17:58:01,691] {standard_task_runner.py:52} INFO - Started process 774 to run task
[2023-11-26 17:58:01,695] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_province', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpmorw9bcf', '--error-file', '/tmp/tmp71spbf4_']
[2023-11-26 17:58:01,696] {standard_task_runner.py:80} INFO - Job 138: Subtask create_dim_province
[2023-11-26 17:58:01,759] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 17:58:01,831] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_province
AIRFLOW_CTX_EXECUTION_DATE=2023-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-21T00:00:00+00:00
[2023-11-26 17:58:01,832] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_data.py", line 38, in create_dim_province
    engine = create_engine(staging_db_constring)
NameError: name 'create_engine' is not defined
[2023-11-26 17:58:01,839] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_covid_etl, task_id=create_dim_province, execution_date=20231121T000000, start_date=20231126T175801, end_date=20231126T175801
[2023-11-26 17:58:01,851] {standard_task_runner.py:97} ERROR - Failed to execute job 138 for task create_dim_province (name 'create_engine' is not defined; 774)
[2023-11-26 17:58:01,866] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-26 17:58:01,901] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:00:55,871] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:00:55,883] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:00:55,883] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:00:55,883] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 18:00:55,884] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:00:55,899] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_province> on 2023-11-21 00:00:00+00:00
[2023-11-26 18:00:55,905] {standard_task_runner.py:52} INFO - Started process 929 to run task
[2023-11-26 18:00:55,908] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_province', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpl19xlm86', '--error-file', '/tmp/tmphaypj2pj']
[2023-11-26 18:00:55,909] {standard_task_runner.py:80} INFO - Job 160: Subtask create_dim_province
[2023-11-26 18:00:55,953] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:00:56,017] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_province
AIRFLOW_CTX_EXECUTION_DATE=2023-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-21T00:00:00+00:00
[2023-11-26 18:00:56,039] {python.py:173} INFO - Done. Returned value was:     province_id province_name
0            32    Jawa Barat
1            32    Jawa Barat
2            32    Jawa Barat
3            32    Jawa Barat
4            32    Jawa Barat
..          ...           ...
140          32    Jawa Barat
141          32    Jawa Barat
142          32    Jawa Barat
143          32    Jawa Barat
144          32    Jawa Barat

[145 rows x 2 columns]
[2023-11-26 18:00:56,051] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-11-26 18:00:56,052] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2380, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 197, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-11-26 18:00:56,061] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_covid_etl, task_id=create_dim_province, execution_date=20231121T000000, start_date=20231126T180055, end_date=20231126T180056
[2023-11-26 18:00:56,073] {standard_task_runner.py:97} ERROR - Failed to execute job 160 for task create_dim_province (Object of type DataFrame is not JSON serializable; 929)
[2023-11-26 18:00:56,120] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-26 18:00:56,163] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:06:09,709] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:06:09,718] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:06:09,718] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:06:09,718] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:06:09,718] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:06:09,733] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_province> on 2023-11-21 00:00:00+00:00
[2023-11-26 18:06:09,738] {standard_task_runner.py:52} INFO - Started process 1200 to run task
[2023-11-26 18:06:09,741] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_province', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp_vkbegmz', '--error-file', '/tmp/tmpl33f0v7i']
[2023-11-26 18:06:09,742] {standard_task_runner.py:80} INFO - Job 205: Subtask create_dim_province
[2023-11-26 18:06:09,795] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:06:09,866] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_province
AIRFLOW_CTX_EXECUTION_DATE=2023-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-21T00:00:00+00:00
[2023-11-26 18:06:09,891] {logging_mixin.py:115} INFO - province_id province_name
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
[2023-11-26 18:06:09,891] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:06:09,904] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_province, execution_date=20231121T000000, start_date=20231126T180609, end_date=20231126T180609
[2023-11-26 18:06:09,953] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:06:09,997] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:08:48,609] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:08:48,617] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:08:48,618] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:08:48,618] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:08:48,618] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:08:48,630] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_province> on 2023-11-21 00:00:00+00:00
[2023-11-26 18:08:48,635] {standard_task_runner.py:52} INFO - Started process 1340 to run task
[2023-11-26 18:08:48,639] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_province', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmprm_37ps3', '--error-file', '/tmp/tmpot5dpe3i']
[2023-11-26 18:08:48,639] {standard_task_runner.py:80} INFO - Job 225: Subtask create_dim_province
[2023-11-26 18:08:48,692] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:08:48,760] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_province
AIRFLOW_CTX_EXECUTION_DATE=2023-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-21T00:00:00+00:00
[2023-11-26 18:08:48,784] {logging_mixin.py:115} INFO - province_id province_name
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
[2023-11-26 18:08:48,787] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "digiskola-postgresql-db-1" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_data.py", line 46, in create_dim_province
    df.to_sql('dim_province', engine_postgres, index=False, if_exists='replace')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1758, in to_sql
    dtype=dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1650, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 856, in create
    if self.exists():
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 840, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1783, in has_table
    insp = sa.inspect(self.connectable)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/inspection.py", line 64, in inspect
    ret = reg(subject)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 182, in _engine_insp
    return Inspector._construct(Inspector._init_engine, bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 117, in _construct
    init(self, bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 128, in _init_engine
    engine.connect().close()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3095, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3174, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3145, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2004, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3141, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 755, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 599, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 583, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "digiskola-postgresql-db-1" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2023-11-26 18:08:48,797] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_covid_etl, task_id=create_dim_province, execution_date=20231121T000000, start_date=20231126T180848, end_date=20231126T180848
[2023-11-26 18:08:48,810] {standard_task_runner.py:97} ERROR - Failed to execute job 225 for task create_dim_province ((psycopg2.OperationalError) could not translate host name "digiskola-postgresql-db-1" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/14/e3q8); 1340)
[2023-11-26 18:08:48,850] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-26 18:08:48,887] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:15:26,705] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:15:26,715] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:15:26,716] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:15:26,716] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:15:26,716] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:15:26,731] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_province> on 2023-11-21 00:00:00+00:00
[2023-11-26 18:15:26,737] {standard_task_runner.py:52} INFO - Started process 1639 to run task
[2023-11-26 18:15:26,738] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_province', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp234qfckl', '--error-file', '/tmp/tmpl3ep6duu']
[2023-11-26 18:15:26,739] {standard_task_runner.py:80} INFO - Job 266: Subtask create_dim_province
[2023-11-26 18:15:26,789] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_province scheduled__2023-11-21T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:15:26,861] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_province
AIRFLOW_CTX_EXECUTION_DATE=2023-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-21T00:00:00+00:00
[2023-11-26 18:15:26,885] {logging_mixin.py:115} INFO - province_id province_name
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
         32    Jawa Barat
[2023-11-26 18:15:26,939] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:15:26,950] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_province, execution_date=20231121T000000, start_date=20231126T181526, end_date=20231126T181526
[2023-11-26 18:15:26,992] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:15:27,035] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
