[2023-11-26 15:39:33,748] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 15:39:33,801] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 15:39:33,801] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:33,801] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 15:39:33,801] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:33,847] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_case> on 2023-11-21 00:00:00+00:00
[2023-11-26 15:39:33,857] {standard_task_runner.py:52} INFO - Started process 2484 to run task
[2023-11-26 15:39:33,862] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_case', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp_n4b3l29', '--error-file', '/tmp/tmpd9lp9p_c']
[2023-11-26 15:39:33,863] {standard_task_runner.py:80} INFO - Job 37: Subtask create_dim_case
[2023-11-26 15:39:33,983] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 15:39:34,457] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-21T00:00:00+00:00
[2023-11-26 15:39:34,458] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 15:39:34,607] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_case, execution_date=20231121T000000, start_date=20231126T153933, end_date=20231126T153934
[2023-11-26 15:39:34,684] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 15:39:34,831] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:57:09,365] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'create_dim_district'}
[2023-11-26 17:57:09,386] {local_task_job.py:101} INFO - Task is not able to be run
[2023-11-26 18:06:11,764] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:06:11,775] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:06:11,775] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:06:11,775] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:06:11,775] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:06:11,789] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_case> on 2023-11-21 00:00:00+00:00
[2023-11-26 18:06:11,794] {standard_task_runner.py:52} INFO - Started process 1206 to run task
[2023-11-26 18:06:11,798] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_case', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpytbm3pkc', '--error-file', '/tmp/tmpoili17ep']
[2023-11-26 18:06:11,799] {standard_task_runner.py:80} INFO - Job 207: Subtask create_dim_case
[2023-11-26 18:06:11,863] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:06:11,933] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-21T00:00:00+00:00
[2023-11-26 18:06:11,933] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:06:11,945] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_case, execution_date=20231121T000000, start_date=20231126T180611, end_date=20231126T180611
[2023-11-26 18:06:11,969] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:06:12,009] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:13:53,011] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:13:53,024] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:13:53,024] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:53,024] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:13:53,024] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:53,046] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_case> on 2023-11-21 00:00:00+00:00
[2023-11-26 18:13:53,052] {standard_task_runner.py:52} INFO - Started process 1531 to run task
[2023-11-26 18:13:53,056] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_case', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpl44y6yqp', '--error-file', '/tmp/tmpo3kirhc8']
[2023-11-26 18:13:53,057] {standard_task_runner.py:80} INFO - Job 244: Subtask create_dim_case
[2023-11-26 18:13:53,114] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:13:53,186] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-21T00:00:00+00:00
[2023-11-26 18:13:53,187] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:13:53,198] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_case, execution_date=20231121T000000, start_date=20231126T181353, end_date=20231126T181353
[2023-11-26 18:13:53,227] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:13:53,282] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:15:29,187] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:15:29,197] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [queued]>
[2023-11-26 18:15:29,197] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:15:29,198] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:15:29,198] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:15:29,214] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_case> on 2023-11-21 00:00:00+00:00
[2023-11-26 18:15:29,220] {standard_task_runner.py:52} INFO - Started process 1646 to run task
[2023-11-26 18:15:29,224] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_case', 'scheduled__2023-11-21T00:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp75yzfyu4', '--error-file', '/tmp/tmp2a6fdaj3']
[2023-11-26 18:15:29,225] {standard_task_runner.py:80} INFO - Job 269: Subtask create_dim_case
[2023-11-26 18:15:29,287] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-21T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:15:29,354] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-21T00:00:00+00:00
[2023-11-26 18:15:29,354] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:15:29,368] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_case, execution_date=20231121T000000, start_date=20231126T181529, end_date=20231126T181529
[2023-11-26 18:15:29,395] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:15:29,453] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
