[2023-11-26 15:39:37,598] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26 15:39:37,659] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26 15:39:37,659] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:37,659] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 15:39:37,659] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:37,730] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_case> on 2023-11-22 00:00:00+00:00
[2023-11-26 15:39:37,744] {standard_task_runner.py:52} INFO - Started process 2545 to run task
[2023-11-26 15:39:37,759] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_case', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp8w6cwp50', '--error-file', '/tmp/tmp74ni2aqb']
[2023-11-26 15:39:37,759] {standard_task_runner.py:80} INFO - Job 54: Subtask create_dim_case
[2023-11-26 15:39:37,906] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-22T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 15:39:38,030] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-11-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-22T00:00:00+00:00
[2023-11-26 15:39:38,030] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 15:39:38,046] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_case, execution_date=20231122T000000, start_date=20231126T153937, end_date=20231126T153938
[2023-11-26 15:39:38,071] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 15:39:38,110] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:57:13,049] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-22T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'create_dim_district'}
[2023-11-26 17:57:13,059] {local_task_job.py:101} INFO - Task is not able to be run
[2023-11-26 18:16:26,923] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26 18:16:26,932] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26 18:16:26,932] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:16:26,932] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:16:26,932] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:16:26,946] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_case> on 2023-11-22 00:00:00+00:00
[2023-11-26 18:16:26,951] {standard_task_runner.py:52} INFO - Started process 1691 to run task
[2023-11-26 18:16:26,954] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_case', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp2xcn1jmc', '--error-file', '/tmp/tmprwk90va4']
[2023-11-26 18:16:26,955] {standard_task_runner.py:80} INFO - Job 274: Subtask create_dim_case
[2023-11-26 18:16:27,024] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-22T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:16:27,093] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-11-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-22T00:00:00+00:00
[2023-11-26 18:16:27,093] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:16:27,105] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_case, execution_date=20231122T000000, start_date=20231126T181626, end_date=20231126T181627
[2023-11-26 18:16:27,125] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:16:27,169] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
