[2023-11-26 15:39:37,081] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 15:39:37,138] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 15:39:37,141] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:37,144] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 15:39:37,144] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:37,221] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_district_daily> on 2023-11-23 00:00:00+00:00
[2023-11-26 15:39:37,263] {standard_task_runner.py:52} INFO - Started process 2539 to run task
[2023-11-26 15:39:37,287] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_district_daily', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmplmhhnf4f', '--error-file', '/tmp/tmp5i3zwpdx']
[2023-11-26 15:39:37,288] {standard_task_runner.py:80} INFO - Job 50: Subtask create_fact_district_daily
[2023-11-26 15:39:37,544] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-23T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 15:39:37,813] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-23T00:00:00+00:00
[2023-11-26 15:39:37,814] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 15:39:37,850] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_district_daily, execution_date=20231123T000000, start_date=20231126T153937, end_date=20231126T153937
[2023-11-26 15:39:37,884] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 15:39:37,941] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:57:12,916] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'create_dim_case'}
[2023-11-26 17:57:12,935] {local_task_job.py:101} INFO - Task is not able to be run
[2023-11-26 18:13:54,210] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 18:13:54,224] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 18:13:54,225] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:54,225] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:13:54,225] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:54,246] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_district_daily> on 2023-11-23 00:00:00+00:00
[2023-11-26 18:13:54,252] {standard_task_runner.py:52} INFO - Started process 1540 to run task
[2023-11-26 18:13:54,255] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_district_daily', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmprfg9e0si', '--error-file', '/tmp/tmprx556ccq']
[2023-11-26 18:13:54,255] {standard_task_runner.py:80} INFO - Job 248: Subtask create_fact_district_daily
[2023-11-26 18:13:54,315] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-23T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:13:54,406] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-23T00:00:00+00:00
[2023-11-26 18:13:54,406] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:13:54,420] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_district_daily, execution_date=20231123T000000, start_date=20231126T181354, end_date=20231126T181354
[2023-11-26 18:13:54,470] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:13:54,510] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:20:31,882] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 18:20:31,892] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 18:20:31,892] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:20:31,892] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:20:31,892] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:20:31,910] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_district_daily> on 2023-11-23 00:00:00+00:00
[2023-11-26 18:20:31,915] {standard_task_runner.py:52} INFO - Started process 1820 to run task
[2023-11-26 18:20:31,918] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_district_daily', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpfim51889', '--error-file', '/tmp/tmpz25ldw21']
[2023-11-26 18:20:31,920] {standard_task_runner.py:80} INFO - Job 285: Subtask create_fact_district_daily
[2023-11-26 18:20:31,985] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-23T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:20:32,067] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-23T00:00:00+00:00
[2023-11-26 18:20:32,068] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:20:32,084] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_district_daily, execution_date=20231123T000000, start_date=20231126T182031, end_date=20231126T182032
[2023-11-26 18:20:32,130] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:20:32,183] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
