[2023-11-26 15:39:33,144] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 15:39:33,176] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 15:39:33,177] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:33,177] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 15:39:33,177] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:33,233] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_case> on 2023-11-20 00:00:00+00:00
[2023-11-26 15:39:33,241] {standard_task_runner.py:52} INFO - Started process 2474 to run task
[2023-11-26 15:39:33,272] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_case', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpxt4k3x4g', '--error-file', '/tmp/tmp0_mab9x9']
[2023-11-26 15:39:33,288] {standard_task_runner.py:80} INFO - Job 25: Subtask create_dim_case
[2023-11-26 15:39:33,460] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-20T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 15:39:33,664] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-11-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-20T00:00:00+00:00
[2023-11-26 15:39:33,664] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 15:39:33,918] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_case, execution_date=20231120T000000, start_date=20231126T153933, end_date=20231126T153933
[2023-11-26 15:39:33,989] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 15:39:34,105] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:57:09,367] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-20T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'create_dim_district'}
[2023-11-26 17:57:09,379] {local_task_job.py:101} INFO - Task is not able to be run
[2023-11-26 18:05:38,474] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 18:05:38,484] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 18:05:38,484] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:05:38,484] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:05:38,484] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:05:38,499] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_case> on 2023-11-20 00:00:00+00:00
[2023-11-26 18:05:38,505] {standard_task_runner.py:52} INFO - Started process 1167 to run task
[2023-11-26 18:05:38,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_case', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpe0t2eek1', '--error-file', '/tmp/tmpozxit002']
[2023-11-26 18:05:38,509] {standard_task_runner.py:80} INFO - Job 198: Subtask create_dim_case
[2023-11-26 18:05:38,556] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-20T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:05:38,623] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-11-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-20T00:00:00+00:00
[2023-11-26 18:05:38,624] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:05:38,634] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_case, execution_date=20231120T000000, start_date=20231126T180538, end_date=20231126T180538
[2023-11-26 18:05:38,679] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:05:38,718] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:13:53,015] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 18:13:53,024] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 18:13:53,024] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:53,024] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:13:53,024] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:53,040] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_dim_case> on 2023-11-20 00:00:00+00:00
[2023-11-26 18:13:53,045] {standard_task_runner.py:52} INFO - Started process 1530 to run task
[2023-11-26 18:13:53,048] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_dim_case', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpceb9abnj', '--error-file', '/tmp/tmp31pb_fo8']
[2023-11-26 18:13:53,048] {standard_task_runner.py:80} INFO - Job 245: Subtask create_dim_case
[2023-11-26 18:13:53,101] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_dim_case scheduled__2023-11-20T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:13:53,175] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_dim_case
AIRFLOW_CTX_EXECUTION_DATE=2023-11-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-20T00:00:00+00:00
[2023-11-26 18:13:53,176] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:13:53,187] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_dim_case, execution_date=20231120T000000, start_date=20231126T181353, end_date=20231126T181353
[2023-11-26 18:13:53,220] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:13:53,270] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
