[2023-11-26 15:39:39,498] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 15:39:39,545] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 15:39:39,545] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:39,553] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 15:39:39,553] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:39,601] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_district_daily> on 2023-11-24 00:00:00+00:00
[2023-11-26 15:39:39,622] {standard_task_runner.py:52} INFO - Started process 2574 to run task
[2023-11-26 15:39:39,635] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_district_daily', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpyjif8pey', '--error-file', '/tmp/tmpdjm2q_w5']
[2023-11-26 15:39:39,635] {standard_task_runner.py:80} INFO - Job 58: Subtask create_fact_district_daily
[2023-11-26 15:39:39,796] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-24T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 15:39:40,028] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-24T00:00:00+00:00
[2023-11-26 15:39:40,029] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 15:39:40,154] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_district_daily, execution_date=20231124T000000, start_date=20231126T153939, end_date=20231126T153940
[2023-11-26 15:39:40,212] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 15:39:40,363] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:57:14,660] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-24T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'create_dim_case'}
[2023-11-26 17:57:14,667] {local_task_job.py:101} INFO - Task is not able to be run
[2023-11-26 18:05:40,903] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 18:05:40,913] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 18:05:40,913] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:05:40,913] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:05:40,913] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:05:40,928] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_district_daily> on 2023-11-24 00:00:00+00:00
[2023-11-26 18:05:40,933] {standard_task_runner.py:52} INFO - Started process 1178 to run task
[2023-11-26 18:05:40,935] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_district_daily', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmphf9tkve7', '--error-file', '/tmp/tmpdgpg86a3']
[2023-11-26 18:05:40,936] {standard_task_runner.py:80} INFO - Job 201: Subtask create_fact_district_daily
[2023-11-26 18:05:40,981] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-24T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:05:41,049] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-24T00:00:00+00:00
[2023-11-26 18:05:41,049] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:05:41,062] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_district_daily, execution_date=20231124T000000, start_date=20231126T180540, end_date=20231126T180541
[2023-11-26 18:05:41,107] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:05:41,142] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:10:56,629] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 18:10:56,639] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-24T00:00:00+00:00 [queued]>
[2023-11-26 18:10:56,639] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:10:56,639] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:10:56,640] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:10:56,654] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_district_daily> on 2023-11-24 00:00:00+00:00
[2023-11-26 18:10:56,659] {standard_task_runner.py:52} INFO - Started process 1417 to run task
[2023-11-26 18:10:56,661] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_district_daily', 'scheduled__2023-11-24T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpk9q3fyxk', '--error-file', '/tmp/tmpu2kcsdda']
[2023-11-26 18:10:56,662] {standard_task_runner.py:80} INFO - Job 231: Subtask create_fact_district_daily
[2023-11-26 18:10:56,705] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-24T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:10:56,770] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-24T00:00:00+00:00
[2023-11-26 18:10:56,771] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:10:56,783] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_district_daily, execution_date=20231124T000000, start_date=20231126T181056, end_date=20231126T181056
[2023-11-26 18:10:56,833] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:10:56,864] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
