[2023-11-26 15:39:33,333] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 15:39:33,391] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 15:39:33,392] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:33,392] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 15:39:33,392] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:33,426] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_district_daily> on 2023-11-20 00:00:00+00:00
[2023-11-26 15:39:33,433] {standard_task_runner.py:52} INFO - Started process 2475 to run task
[2023-11-26 15:39:33,451] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_district_daily', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp0aur3uxh', '--error-file', '/tmp/tmp3id881xb']
[2023-11-26 15:39:33,451] {standard_task_runner.py:80} INFO - Job 27: Subtask create_fact_district_daily
[2023-11-26 15:39:33,604] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-20T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 15:39:33,814] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-20T00:00:00+00:00
[2023-11-26 15:39:33,815] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 15:39:33,946] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_district_daily, execution_date=20231120T000000, start_date=20231126T153933, end_date=20231126T153933
[2023-11-26 15:39:33,992] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 15:39:34,065] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:57:09,333] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-20T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'create_dim_case'}
[2023-11-26 17:57:09,344] {local_task_job.py:101} INFO - Task is not able to be run
[2023-11-26 18:05:39,648] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 18:05:39,658] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 18:05:39,658] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:05:39,658] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:05:39,658] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:05:39,673] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_district_daily> on 2023-11-20 00:00:00+00:00
[2023-11-26 18:05:39,678] {standard_task_runner.py:52} INFO - Started process 1172 to run task
[2023-11-26 18:05:39,681] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_district_daily', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp253nkuif', '--error-file', '/tmp/tmpefimz1e8']
[2023-11-26 18:05:39,682] {standard_task_runner.py:80} INFO - Job 199: Subtask create_fact_district_daily
[2023-11-26 18:05:39,733] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-20T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:05:39,804] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-20T00:00:00+00:00
[2023-11-26 18:05:39,805] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:05:39,817] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_district_daily, execution_date=20231120T000000, start_date=20231126T180539, end_date=20231126T180539
[2023-11-26 18:05:39,853] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:05:39,887] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:13:54,170] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 18:13:54,185] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2023-11-26 18:13:54,186] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:54,186] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:13:54,187] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:54,203] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_district_daily> on 2023-11-20 00:00:00+00:00
[2023-11-26 18:13:54,209] {standard_task_runner.py:52} INFO - Started process 1538 to run task
[2023-11-26 18:13:54,212] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_district_daily', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpvyxq6c5a', '--error-file', '/tmp/tmpvptdhnq7']
[2023-11-26 18:13:54,213] {standard_task_runner.py:80} INFO - Job 246: Subtask create_fact_district_daily
[2023-11-26 18:13:54,273] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_district_daily scheduled__2023-11-20T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:13:54,366] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-20T00:00:00+00:00
[2023-11-26 18:13:54,369] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:13:54,382] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_district_daily, execution_date=20231120T000000, start_date=20231126T181354, end_date=20231126T181354
[2023-11-26 18:13:54,424] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:13:54,460] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
