[2023-11-26 14:29:43,635] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.ingest_staging_db scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26 14:29:43,645] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.ingest_staging_db scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26 14:29:43,645] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 14:29:43,645] {taskinstance.py:1357} INFO - Starting attempt 2 of 7
[2023-11-26 14:29:43,645] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 14:29:43,660] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): ingest_staging_db> on 2023-11-22 00:00:00+00:00
[2023-11-26 14:29:43,665] {standard_task_runner.py:52} INFO - Started process 770 to run task
[2023-11-26 14:29:43,668] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'ingest_staging_db', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpm4xhk1ra', '--error-file', '/tmp/tmpwdm3so6s']
[2023-11-26 14:29:43,668] {standard_task_runner.py:80} INFO - Job 23: Subtask ingest_staging_db
[2023-11-26 14:29:43,717] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.ingest_staging_db scheduled__2023-11-22T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 14:29:43,791] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=ingest_staging_db
AIRFLOW_CTX_EXECUTION_DATE=2023-11-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-22T00:00:00+00:00
[2023-11-26 14:29:44,421] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 14:29:44,433] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=ingest_staging_db, execution_date=20231122T000000, start_date=20231126T142943, end_date=20231126T142944
[2023-11-26 14:29:44,484] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 14:29:44,511] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:57:53,414] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.ingest_staging_db scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26 17:57:53,425] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.ingest_staging_db scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26 17:57:53,425] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 17:57:53,425] {taskinstance.py:1357} INFO - Starting attempt 2 of 7
[2023-11-26 17:57:53,425] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 17:57:53,438] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): ingest_staging_db> on 2023-11-22 00:00:00+00:00
[2023-11-26 17:57:53,445] {standard_task_runner.py:52} INFO - Started process 759 to run task
[2023-11-26 17:57:53,447] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'ingest_staging_db', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpduwlqjd5', '--error-file', '/tmp/tmp8kp1fmvw']
[2023-11-26 17:57:53,448] {standard_task_runner.py:80} INFO - Job 135: Subtask ingest_staging_db
[2023-11-26 17:57:53,496] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.ingest_staging_db scheduled__2023-11-22T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 17:57:53,567] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=ingest_staging_db
AIRFLOW_CTX_EXECUTION_DATE=2023-11-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-22T00:00:00+00:00
[2023-11-26 17:57:54,125] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 17:57:54,137] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=ingest_staging_db, execution_date=20231122T000000, start_date=20231126T175753, end_date=20231126T175754
[2023-11-26 17:57:54,182] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 17:57:54,313] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:13:48,704] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.ingest_staging_db scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26 18:13:48,718] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.ingest_staging_db scheduled__2023-11-22T00:00:00+00:00 [queued]>
[2023-11-26 18:13:48,718] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:48,718] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2023-11-26 18:13:48,718] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:48,745] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): ingest_staging_db> on 2023-11-22 00:00:00+00:00
[2023-11-26 18:13:48,749] {standard_task_runner.py:52} INFO - Started process 1498 to run task
[2023-11-26 18:13:48,755] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'ingest_staging_db', 'scheduled__2023-11-22T00:00:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpyfgqzjfu', '--error-file', '/tmp/tmpxxx88v1f']
[2023-11-26 18:13:48,755] {standard_task_runner.py:80} INFO - Job 236: Subtask ingest_staging_db
[2023-11-26 18:13:48,823] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.ingest_staging_db scheduled__2023-11-22T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:13:48,917] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=ingest_staging_db
AIRFLOW_CTX_EXECUTION_DATE=2023-11-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-22T00:00:00+00:00
[2023-11-26 18:13:49,328] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1051, "Unknown table 'finalproject.covid_jabar'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_data.py", line 35, in ingest_data_staging
    df.to_sql("covid_jabar", staging_db_constring, if_exists="replace", index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1758, in to_sql
    dtype=dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1650, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 860, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1810, in drop_table
    self.get_table(table_name, schema).drop()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 960, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3008, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2016, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 1097, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 78, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1296, in _execute_ddl
    compiled,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1051, "Unknown table 'finalproject.covid_jabar'")
[SQL: 
DROP TABLE covid_jabar]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2023-11-26 18:13:49,341] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_covid_etl, task_id=ingest_staging_db, execution_date=20231122T000000, start_date=20231126T181348, end_date=20231126T181349
[2023-11-26 18:13:49,356] {standard_task_runner.py:97} ERROR - Failed to execute job 236 for task ingest_staging_db ((MySQLdb._exceptions.OperationalError) (1051, "Unknown table 'finalproject.covid_jabar'")
[SQL: 
DROP TABLE covid_jabar]
(Background on this error at: http://sqlalche.me/e/14/e3q8); 1498)
[2023-11-26 18:13:49,372] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-26 18:13:49,435] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
