[2023-11-26 15:39:37,350] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 15:39:37,405] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 15:39:37,406] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:37,406] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-11-26 15:39:37,406] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 15:39:37,496] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_province_daily> on 2023-11-23 00:00:00+00:00
[2023-11-26 15:39:37,510] {standard_task_runner.py:52} INFO - Started process 2541 to run task
[2023-11-26 15:39:37,514] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_province_daily', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmp2kdu2fow', '--error-file', '/tmp/tmp386wt_kg']
[2023-11-26 15:39:37,515] {standard_task_runner.py:80} INFO - Job 52: Subtask create_fact_province_daily
[2023-11-26 15:39:37,674] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-23T00:00:00+00:00 [running]> on host f384f2afcc4f
[2023-11-26 15:39:37,836] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-23T00:00:00+00:00
[2023-11-26 15:39:37,837] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 15:39:37,875] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_province_daily, execution_date=20231123T000000, start_date=20231126T153937, end_date=20231126T153937
[2023-11-26 15:39:37,918] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 15:39:37,972] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 17:57:12,982] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'create_fact_district_daily'}
[2023-11-26 17:57:12,989] {local_task_job.py:101} INFO - Task is not able to be run
[2023-11-26 18:13:55,485] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 18:13:55,505] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 18:13:55,505] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:55,505] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:13:55,505] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:13:55,545] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_province_daily> on 2023-11-23 00:00:00+00:00
[2023-11-26 18:13:55,550] {standard_task_runner.py:52} INFO - Started process 1549 to run task
[2023-11-26 18:13:55,559] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_province_daily', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmpqhrn8z6b', '--error-file', '/tmp/tmppo04n8dj']
[2023-11-26 18:13:55,559] {standard_task_runner.py:80} INFO - Job 251: Subtask create_fact_province_daily
[2023-11-26 18:13:55,614] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-23T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:13:55,689] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-23T00:00:00+00:00
[2023-11-26 18:13:55,690] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:13:55,704] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_province_daily, execution_date=20231123T000000, start_date=20231126T181355, end_date=20231126T181355
[2023-11-26 18:13:55,729] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:13:55,769] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-26 18:20:33,204] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 18:20:33,223] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26 18:20:33,224] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:20:33,224] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-11-26 18:20:33,224] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-11-26 18:20:33,243] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_fact_province_daily> on 2023-11-23 00:00:00+00:00
[2023-11-26 18:20:33,248] {standard_task_runner.py:52} INFO - Started process 1823 to run task
[2023-11-26 18:20:33,251] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_covid_etl', 'create_fact_province_daily', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/get_data.py', '--cfg-path', '/tmp/tmppcocd2cy', '--error-file', '/tmp/tmp89rrdh5i']
[2023-11-26 18:20:33,251] {standard_task_runner.py:80} INFO - Job 286: Subtask create_fact_province_daily
[2023-11-26 18:20:33,301] {task_command.py:369} INFO - Running <TaskInstance: data_covid_etl.create_fact_province_daily scheduled__2023-11-23T00:00:00+00:00 [running]> on host 79a606f4be36
[2023-11-26 18:20:33,371] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=oce
AIRFLOW_CTX_DAG_ID=data_covid_etl
AIRFLOW_CTX_TASK_ID=create_fact_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-23T00:00:00+00:00
[2023-11-26 18:20:33,372] {python.py:173} INFO - Done. Returned value was: None
[2023-11-26 18:20:33,384] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_covid_etl, task_id=create_fact_province_daily, execution_date=20231123T000000, start_date=20231126T182033, end_date=20231126T182033
[2023-11-26 18:20:33,423] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-11-26 18:20:33,454] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
